spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: ${APPLICATION_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

memo:
  jwt:
    secret: ${JWT_SECRET}
    expirationInMs: 3600000